baseURL: 'https://artosalminen.github.io/'
languageCode: 'en-us'
title: "Arto's dev time by-products"
theme: 'PaperMod'

paginate: 5

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

googleAnalytics: G-WNZM3KSNKG

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

languages:
  en:
    languageName: 'English'
    weight: 1
    taxonomies:
      category: categories
      tag: tags
      series: series
    menu:
      main:
        - name: Archive
          url: archives
          weight: 5
        - name: Search
          url: search/
          weight: 10

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  description: 'Personal ramblings about code and stuff'
  keywords: [Blog, Portfolio]
  author: Arto Salminen
  # author: ["Me", "You"] # multiple authors
  # images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: 'January 2, 2006'
  defaultTheme: dark #, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  # disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: true
  hideSummary: false
  showtoc: false
  tocopen: false

  assets:
    disableHLJS: true
    favicon: "favicon.png"
    favicon32x32: "favicon.png"
  #     favicon16x16: "<link / abs url>"
  #     apple_touch_icon: "<link / abs url>"
  #     safari_pinned_tab: "<link / abs url>"

  homeInfoParams:
    Title: 'Hello fellow!'
    Content: Feel free to browse my coding related notes

  social: true
  socialIcons:
    - name: github
      url: 'https://github.com/artosalminen'
    - name: LinkedIn
      url: 'https://www.linkedin.com/in/artosalminen/'
    - name: Rss
      url: 'index.xml'

  editPost:
    URL: 'https://github.com/artosalminen/artosalminen.github.io/tree/main/content'
    Text: 'Suggest Changes' # edit text
    appendFilePath: true # to append file path to Edit link

services:
  instagram:
    disableInlineCSS: true
  twitter:
    disableInlineCSS: true
